
name: 'Tests'

on:
  schedule:
    - cron: '0 4 1 * *'
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  mvn15:
    name: Maven & java 15
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./ci/mvn.Dockerfile
          build-args: MVN_VERSION=3.8.1-openjdk-15-slim
          push: false
  mvn16:
    name: Maven & java 16
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./ci/mvn.Dockerfile
          build-args: MVN_VERSION=3.8.3-openjdk-16-slim
          push: false
  mvn17:
    name: Maven & java 17
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./ci/mvn.Dockerfile
          build-args: MVN_VERSION=3.8.3-openjdk-17-slim
          push: false
  gradle15:
    name: Gradle & java 15
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./ci/gradle.Dockerfile
          build-args: GRADLE_VERSION=6.8.3-jdk15
          push: false
  gradle16:
    name: Gradle & java 16
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./ci/gradle.Dockerfile
          build-args: GRADLE_VERSION=7.2.0-jdk16
          push: false
  gradle17:
    name: Gradle & java 17
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./ci/gradle.Dockerfile
          build-args: GRADLE_VERSION=7.2.0-jdk17
          push: false

