
name: 'Tests'

on:
  schedule:
    - cron: '0 4 1 * *'
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  mvn15:
    name: Maven & java 15
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./ci/mvn_java15.Dockerfile
          push: false
  mvn17:
    name: Maven & java 17
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./ci/mvn_java17.Dockerfile
          push: false
  gradle15:
    name: Gradle & java 15
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./ci/gradle_java15.Dockerfile
          push: false
  gradle17:
    name: Gradle & java 17
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./ci/gradle_java17.Dockerfile
          push: false

